# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2017-03-23 06:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_remove_urlnav_pub_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='suburlnav',
            name='suburlnav',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='polls.UrlNav'),
            preserve_default=False,
        ),
    ]
