# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2017-03-22 06:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_saveurlnavtodb_urlnav'),
    ]

    operations = [
        migrations.DeleteModel(
            name='saveUrlNavToDB',
        ),
    ]
