# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2017-03-23 07:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_suburlnav_suburlnav'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suburlnav',
            name='subUrlNavheader',
            field=models.TextField(),
        ),
    ]
