# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2017-03-22 07:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_delete_saveurlnavtodb'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='urlnav',
            name='pub_date',
        ),
    ]
