# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2017-03-24 03:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('restaurantName', models.CharField(max_length=200)),
                ('restaurantAddress', models.CharField(max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='urlnav',
            name='pub_date',
        ),
        migrations.AddField(
            model_name='suburlnav',
            name='suburlnav',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='polls.UrlNav'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='suburlnav',
            name='subUrlNavheader',
            field=models.TextField(),
        ),
    ]
