# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-25 21:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20170323_2036'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
