# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2017-03-28 04:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_blogpost'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='restaurantLatLng',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
    ]
